# Configuración global de Netlify
[build]
  publish = "/"
  
# Configuración de redirecciones
[[redirects]]
  from = "/thank-you-page"
  to = "/thank-you-page.html"
  status = 200

# Configuración para formularios
[forms]
  [forms.contact]
    name = "contact"
    success_url = "/thank-you-page.html"